version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    groups:
      github_actions_security:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - "ci"
      - "security"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    groups:
      gomod_security:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
